<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Helper;

use Guite\KnowledgeBaseModule\Helper\Base\SearchHelper as BaseSearchHelper;

/**
 * Search helper implementation class.
 */
class SearchHelper extends BaseSearchHelper
{
    // feel free to extend the search helper here
}
