<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 20:13:48 CET 2012.
 */


/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for ticket entities.
 */
class KnowledgeBase_Entity_Validator_Ticket extends KnowledgeBase_Entity_Validator_Base_Ticket
{
    // here you can add custom validation methods or override existing checks
}
