<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule;

use Guite\KnowledgeBaseModule\Base\GuiteKnowledgeBaseModule as BaseGuiteKnowledgeBaseModule;

/**
 * Module implementation class.
 */
class GuiteKnowledgeBaseModule extends BaseGuiteKnowledgeBaseModule
{
    // custom enhancements can go here
}
