<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule;

use Guite\KnowledgeBaseModule\Base\KnowledgeBaseModuleInstaller as BaseKnowledgeBaseModuleInstaller;

/**
 * Installer implementation class.
 */
class KnowledgeBaseModuleInstaller extends BaseKnowledgeBaseModuleInstaller
{
    // feel free to extend the installer here
}
