<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Fri Feb 28 08:31:01 CET 2014.
 */

namespace Guite\KnowledgeBaseModule;

use Guite\KnowledgeBaseModule\Base\KnowledgeBaseModuleVersion as BaseKnowledgeBaseModuleVersion;

/**
 * Version information implementation class.
 */
class KnowledgeBaseModuleVersion extends BaseKnowledgeBaseModuleVersion
{
    // custom enhancements can go here
}
