<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) 2009, Zikula Development Team
 * @link http://www.zikula.org
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Zikula_Generated_Modules
 * @subpackage KnowledgeBase
 * @author Axel Guckelsberger
 * @url https://guite.de
 */

/*
 * generated at Wed Apr 07 21:54:26 CEST 2010 by ModuleStudio 0.4.10 (http://modulestudio.de)
 */

// retrieve gettext domain for this module
$dom = ZLanguage::getModuleDomain('KnowledgeBase');

// define the name of the module
$modversion['name']           = 'KnowledgeBase';
// define the displayed name of the module
$modversion['displayname']    = __('KnowledgeBase', $dom);
// define the module description
$modversion['description']    = __('KnowledgeBase module generated by ModuleStudio 0.4.10', $dom);
// url version of name
$modversion['url']            = __('knowledgebase', $dom);
// define the current module version
$modversion['version']        = '1.0';

// file with credit information
$modversion['credits']        = 'docs/credits.txt';
// help file
$modversion['help']           = 'docs/readme.txt';
// changelog file
$modversion['changelog']      = 'docs/changelog.txt';
// file with license information
$modversion['license']        = 'docs/license.txt';

// this is no official core / system module
$modversion['official']       = 0;
// the module author
$modversion['author']         = 'Axel Guckelsberger';
// module homepage
$modversion['contact']        = 'https://guite.de';

// we do not have an admin area
$modversion['admin']          = 0;
// we do have a user area
$modversion['user']           = 1;

// permission schema



