<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Block;

use Guite\KnowledgeBaseModule\Block\Base\ItemListBlock as BaseItemListBlock;

/**
 * Generic item list block implementation class.
 */
class ItemListBlock extends BaseItemListBlock
{
    // feel free to extend the item list block here
}
