<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Entity\Validator;

use Guite\KnowledgeBaseModule\Entity\Validator\Base\TicketValidator as BaseTicketValidator;

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for ticket entities.
 */
class TicketValidator extends BaseTicketValidator
{
    // here you can add custom validation methods or override existing checks
}
