<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */

/**
 * Installer implementation class
 */
class KnowledgeBase_Installer extends KnowledgeBase_Base_Installer
{
    /**
     * Install the KnowledgeBase application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        $result = parent::install();

        // create the default categories for KnowledgeBase
        if (!$this->createDefaultCategories()) {
            return LogUtil::registerError(__('creation of default categories failed', $dom));
        }
        return true;
    }

    /**
     * create the default categories for KnowledgeBase
     *
     * @author       Axel Guckelsberger
     * @return       bool       true if successful or false if something went wrong
     */
    private function createDefaultCategories()
    {
        ModUtil::dbInfoLoad('Categories');

        $tables = DBUtil::getTables();

        $catcolumn = $tables['categories_category_column'];
        $where = '';
        $orderBy = " $catcolumn[id] DESC";
        $lastCat = DBUtil::selectObjectArray('categories_category', $where, $orderBy, 0, 1); //LIMIT 0, 1
        if ($lastCat === false || !$lastCat) {
            return false;
        }

        //we have only one item
        $lastCat = $lastCat[0];

        $nextCatID = $lastCat['id'] + 1;

        $objArray = array();

        $parentList = array();
        $rootCat = array();
        $parentLvlOne = array();
        $parentLvlTwo = array();


        $catNames = array('en' => 'Knowledge Base',
                          'de' => 'Knowledge Base');
        $catDescriptions = array('en' => 'Main category for the Knowledge Base',
                                 'de' => 'Hauptkategorie für die Knowledge Base');
        $rootCat = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

        $parentList = array($rootCat);                  // reset to level one
        $catNames = array('en' => 'Ticket Categories',
                          'de' => 'Ticket-Kategorien');
        $catDescriptions = array('en' => 'Available topics for tickets',
                                 'de' => 'Verfügbare Themen für Tickets');
        $parentLvlOne = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

        $parentList = array($rootCat, $parentLvlOne);   // reset to level two
        {
            $catNames = array('en' => 'Installation',
                              'de' => 'Installation');
            $catDescriptions = array('eng' => 'Installation of Zikula',
                                     'deu' => 'Installation von Zikula');
            $parentLvlTwo = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

            $catNames = array('en' => 'Configuration',
                              'de' => 'Konfiguration');
            $catDescriptions = array('eng' => 'Configure Zikula and basic settings',
                                     'deu' => 'Zikula konfigurieren und Grundeinstellungen');
            $parentLvlTwo = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

            $catNames = array('en' => 'Modules',
                              'de' => 'Module');
            $catDescriptions = array('eng' => 'Setup, manage and use modules',
                                     'deu' => 'Module einrichten, verwalten und verwenden');
            $parentLvlTwo = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

            $catNames = array('en' => 'Themes',
                              'de' => 'Themes');
            $catDescriptions = array('eng' => 'Design your layout in Zikula',
                                     'deu' => 'Realisiere Dein Design mit Zikula');
            $parentLvlTwo = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

            $catNames = array('en' => 'Customisation',
                              'de' => 'Anpassung');
            $catDescriptions = array('eng' => 'Your individual Zikula',
                                     'deu' => 'Individualisierung von Zikula');
            $parentLvlTwo = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

            $catNames = array('en' => 'Development',
                              'de' => 'Entwicklung');
            $catDescriptions = array('eng' => 'Development of and for Zikula',
                                     'deu' => 'Entwicklung von und für Zikula');
            $parentLvlTwo = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);

            $catNames = array('en' => 'Tools and Services',
                              'de' => 'Nützliche Werkzeuge');
            $catDescriptions = array('eng' => 'CoZi, extension database and further tools',
                                     'deu' => 'CoZi, Extension-Datenbank und andere Tools');
            $parentLvlTwo = $this->createSingleCategoryArray($nextCatID++, $parentList, $catNames, $catDescriptions, $objArray);
        }

        // insert the categories records
        DBUtil::insertObjectArray($objArray, 'categories_category', 'id', true);


        // rebuild all path entries so that we can use them below
        CategoryUtil::rebuildPaths('path', 'name');
        CategoryUtil::rebuildPaths('ipath', 'id');

        // define category registration mappings to ticket table
        $mappingRootCats = array(
            array('prop' => 'TicketCategoryMain', 'rootPath' => '/__SYSTEM__/Knowledge Base/Ticket Categories'));

        foreach ($mappingRootCats as $mappingRoot) {
            $rootCat = CategoryUtil::getCategoryByPath($mappingRoot['rootPath']);

            $registry = new Categories_DBObject_Registry();
            $registry->setDataField('modname', 'KnowledgeBase');
            $registry->setDataField('table', 'kbase_ticket');
            $registry->setDataField('property', $mappingRoot['prop']);
            $registry->setDataField('category_id', $rootCat['id']);
            $registry->insert();

            $this->setVar('baseCat' . $mappingRoot['prop'], $mappingRoot['rootPath']);
        }

        return true;
    }


    private function createSingleCategoryArray($catID, $parentArray, $catNames, $catDescriptions, &$destArray) {
        $path = '/__SYSTEM__/Knowledge Base';
        $ipath = '';
        $numParents = count($parentArray);
        if ($numParents > 0) {
            foreach($parentArray as $parentCat) {
                $path .= '/' . $parentCat['name'];
                $ipath = '/' . $parentCat['id'];
            }
        }

        $ipath .= '/' . $catID;

        $newCatArray = array(
            'id'               => $catID,
            'parent_id'        => ($numParents > 0) ? $parentArray[$numParents-1]['id'] : 1,
            'is_locked'        => 0,
            'is_leaf'          => 0,
            'name'             => $catNames['en'],
            'display_name'     => serialize($catNames),
            'display_desc'     => serialize($catDescriptions),
            'path'             => $path,
            'ipath'            => $ipath,
            'status'           => 'A');

        $destArray[] = $newCatArray;
        return $newCatArray;
    }
}
