<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 20:13:48 CET 2012.
 */

/**
 * This handler class handles the page events of the Form called by the KnowledgeBase_user_edit() function.
 * It collects common functionality required by different object types.
 */
class KnowledgeBase_Form_Handler_User_Edit extends KnowledgeBase_Form_Handler_User_Base_Edit
{
    // feel free to extend the base handler class here
}
