<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 20:13:48 CET 2012.
 */

/**
 * Generic item list content plugin implementation class
 */
class KnowledgeBase_ContentType_ItemList extends KnowledgeBase_ContentType_Base_ItemList
{
    // feel free to extend the content type here
}

function KnowledgeBase_Api_ContentTypes_itemlist($args)
{
    return new KnowledgeBase_Api_ContentTypes_itemListPlugin();
}
