<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\ContentType;

use Guite\KnowledgeBaseModule\ContentType\Base\ItemList as BaseItemList;

/**
 * Generic item list content plugin implementation class.
 */
class ItemList extends BaseItemList
{
    // feel free to extend the content type here
}
