<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */

/**
 * This is the Admin api helper class.
 */
class KnowledgeBase_Api_Base_Admin extends Zikula_Api
{
    /**
     * get available Admin panel links
     *
     * @return       array      array of admin links
     */
    public function getlinks()
    {
        $links = array();

        if (SecurityUtil::checkPermission('KnowledgeBase::', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url('KnowledgeBase', 'admin', 'main'),
                             'text' => $this->__('Admin main page'),
                             'title' => $this->__('KnowledgeBase administration.'));
        }
        $links[] = array('url' => ModUtil::url('KnowledgeBase', 'user', 'main'),
                            'text' => $this->__('User area'),
                            'title' => $this->__('Go to user main page.'));

        return $links;
    }
}
