<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */

/**
 * This is the Ajax api helper class.
 */
class KnowledgeBase_Api_Base_Ajax extends Zikula_Api
{
    /**
     * get available Ajax panel links
     *
     * @return       array      array of admin links
     */
    public function getlinks()
    {
        $links = array();

        return $links;
    }
}
