<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 20:13:48 CET 2012.
 */

/**
 * This is the Ajax api helper class.
 */
class KnowledgeBase_Api_Base_Ajax extends Zikula_AbstractApi
{
    /**
     * get available Ajax panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        return $links;
    }
}
