<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */

/**
 * Smarty function to process hierarchical list structures by given level information
 *
 * Available parameters:
 *   - assign:  If set, the result is assigned to the corresponding variable instead of printed out
 *
 * @param        array       $params      All attributes passed to this function from the template
 * @param        object      &$smarty     Reference to the Smarty object
 * @param        string      $assign      (optional) The name of the variable to assign the result to
 * @return       string      The recent users language
 */
function smarty_function_kbProcessListLevels($params, &$render)
{
    $dom = ZLanguage::getModuleDomain('KnowledgeBase');
    if (!isset($params['level']) || !isset($params['lastlevel'])) {
        $render->trigger_error(__f('%1$s: missing parameter \'%2$s\'', array('smarty_function_kbProcessListLevels', 'lastlevel'), $dom));
    }

    $result = '';

    $level = (is_numeric($params['level'])) ? $params['level'] : count(explode('.', $params['level']));
    $lastLevel = (is_numeric($params['lastlevel'])) ? $params['lastlevel'] : count(explode('.', $params['lastlevel']));

    $opened = false;
    if ($lastLevel > 0) {
        if ($level > $lastLevel) {
            while ($level > $lastLevel) {
                $result .= '<ul>';
                $level--;
            }
            $opened = true;

        } elseif ($level < $lastLevel) {
            while ($level < $lastLevel) {
                $result .= '</li></ul>';
                $level++;
            }
        }
        if (!$opened) {
            $result .= '</li>';
        }
    }

    if (isset($assign)) {
        $smarty->assign($assign, $result);
        return;
    }

    return $result;
}
