<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Api\Base;

use Guite\KnowledgeBaseModule\Util\ControllerUtil;
use LogUtil;
use ModUtil;
use SecurityUtil;
use Zikula_AbstractApi;

/**
 * This is the Ajax api helper class.
 */
class AjaxApi extends Zikula_AbstractApi
{
}
