<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Form\Plugin;

use Guite\KnowledgeBaseModule\Form\Plugin\Base\ItemSelector as BaseItemSelector;

/**
 * Item selector plugin implementation class.
 */
class ItemSelector extends BaseItemSelector
{
    // feel free to add your customisation here
}
