<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Controller\Base;

use Guite\KnowledgeBaseModule\Util\ControllerUtil;
use Guite\KnowledgeBaseModule\Util\ViewUtil;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use FormUtil;
use LogUtil;
use ModUtil;
use SecurityUtil;
use Zikula_AbstractController;
use Zikula_View;
use ZLanguage;
use Zikula\Core\ModUrl;
use Zikula\Core\Response\PlainResponse;

/**
 * Admin controller class.
 */
class AdminController extends Zikula_AbstractController
{
    /**
     * Post initialise.
     *
     * Run after construction.
     *
     * @return void
     */
    protected function postInitialize()
    {
        // Set caching to false by default.
        $this->view->setCaching(Zikula_View::CACHE_DISABLED);
    }

    /**
     * This method is the default function handling the admin area called without defining arguments.
     *
     *
     * @return mixed Output.
     *
     * @throws AccessDeniedException Thrown if the user doesn't have required permissions
     */
    public function indexAction(Request $request)
    {
        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            throw new AccessDeniedException();
        }
        // set caching id
        $this->view->setCacheId('index');
        
        
        // return index template
        return $this->response($this->view->fetch('Admin/index.tpl'));
        
    }
    
}
