<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Util;

use Guite\KnowledgeBaseModule\Util\Base\ListEntriesUtil as BaseListEntriesUtil;

/**
 * Utility implementation class for list field entries related methods.
 */
class ListEntriesUtil extends BaseListEntriesUtil
{
    // feel free to add your own convenience methods here
}
