<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Util;

use Guite\KnowledgeBaseModule\Util\Base\ModelUtil as BaseModelUtil;

/**
 * Utility implementation class for model helper methods.
 */
class ModelUtil extends BaseModelUtil
{
    // feel free to add your own convenience methods here
}
