<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Fri Feb 28 08:31:01 CET 2014.
 */

namespace Guite\KnowledgeBaseModule\DependencyInjection;

use Guite\KnowledgeBaseModule\DependencyInjection\Base\GuiteKnowledgeBaseExtension as BaseGuiteKnowledgeBaseExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class GuiteKnowledgeBaseExtension extends BaseGuiteKnowledgeBaseExtension
{
    // custom enhancements can go here
}
