<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Feb 17 15:26:09 CET 2011.
 */

/**
 * Utility implementation class for controller helper methods.
 */
class KnowledgeBase_Util_Controller extends KnowledgeBase_Util_Base_Controller
{
    /**
     * retrieve subdata arrays
     */
    function postProcessTicket($data = null)
    {
        if (is_null($data) || !$data) {
            return $data;
        }

        $currentType = FormUtil::getPassedValue('type', 'user', 'GETPOST', FILTER_SANITIZE_STRING);
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
        $idField = 'ticketid';

        if (is_object($data)) {
            $data->mapValue('subjectStripped', str_replace('"', '\'', $data['subject']));

            $data->mapValue('detailurl', ModUtil::url('KnowledgeBase', 'user', 'display', array('id' => $data[$idField])));
            $data->mapValue('detailurlFormatted', DataUtil::formatForDisplay($data['detailurl']));

            $data->mapValue('editurl', ModUtil::url('KnowledgeBase', 'user', 'edit', array('id' => $data[$idField])));
            $data->mapValue('editurlFormatted', DataUtil::formatForDisplay($data['editurl']));
        }
        else {
            $data['subjectStripped'] = str_replace('"', '\'', $data['subject']);

            $data['detailurl'] = ModUtil::url('KnowledgeBase', 'user', 'display', array('id' => $data[$idField]));
            $data['detailurlFormatted'] = DataUtil::formatForDisplay($data['detailurl']);

            $data['editurl'] = ModUtil::url('KnowledgeBase', 'user', 'edit', array('id' => $data[$idField]));
            $data['editurlFormatted'] = DataUtil::formatForDisplay($data['editurl']);
        }

        return $data;
    }
}
