<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */


// feel free to add your initialisation stuff here

// for example you can register additional AutoLoaders with ZLoader::addAutoloader($namespace, $path)
// whereby $namespace is the first part of the PEAR class name and $path is the path to the containing
// folder.

