<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Zikula\Core\Doctrine\Entity\AbstractEntityCategory;

/**
 * Entity extension domain class storing ticket categories.
 *
 * This is the base category class for ticket entities.
 */
abstract class AbstractTicketCategoryEntity extends AbstractEntityCategory
{
    /**
     * @ORM\ManyToOne(targetEntity="\Guite\KnowledgeBaseModule\Entity\TicketEntity", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var \Guite\KnowledgeBaseModule\Entity\TicketEntity
     */
    protected $entity;

    /**
     * Get reference to owning entity.
     *
     * @return \Guite\KnowledgeBaseModule\Entity\TicketEntity
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param \Guite\KnowledgeBaseModule\Entity\TicketEntity $entity
     */
    public function setEntity(/*\Guite\KnowledgeBaseModule\Entity\TicketEntity */$entity)
    {
        $this->entity = $entity;
    }
}
