<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Feb 17 14:43:00 CET 2011.
 */

/**
 * Version information base class.
 */
class KnowledgeBase_Base_Version extends Zikula_AbstractVersion
{
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version'] = '1.0.0';
        // the displayed name of the module
        $meta['displayname'] = $this->__('KnowledgeBase');
        // the module description
        $meta['description'] = $this->__('The knowledge base module provides a categorised archive for recurring questions and answers to improve community support.');
        //! url version of name, should be in lowercase without space
        $meta['url'] = $this->__('KnowledgeBase');
        // minimum core requirement
        $meta['core_min'] = '1.3.0'; // requires minimum 1.3.0 or later

        // define special capabilities of this module
        $meta['capabilities'] = array(
            HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true) /*,
             HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #115
             'authentication' => array('version' => '1.0'),
             'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
             'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
             */
        );

        // permission schema
        // DEBUG: permission schema aspect starts
        $meta['securityschema'] = array(
            'KnowledgeBase::'       => '::',

            'KnowledgeBase:Ticket:' => 'TicketID::'
        );
        // DEBUG: permission schema aspect ends

        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {

        $bundle = new Zikula_Version_HookSubscriberBundle('modulehook_area.knowledgebase.tickets', __('Tickets'));
        // Display hook for view/display templates.
        $bundle->addType('ui.view', 'knowledgebase.hook.tickets.ui.view');
        // Display hook for create/edit forms.
        $bundle->addType('ui.edit', 'knowledgebase.hook.tickets.ui.edit');
        // Display hook for delete dialogues (generally not used).
        $bundle->addType('ui.delete', 'knowledgebase.hook.tickets.ui.delete');
        // Validate input from an ui create/edit form.
        $bundle->addType('validate.edit', 'knowledgebase.hook.tickets.validate.edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addType('validate.delete', 'knowledgebase.hook.tickets.validate.delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addType('process.edit', 'knowledgebase.hook.tickets.process.edit');
        // Perform the final delete actions for a ui form.
        $bundle->addType('process.delete', 'knowledgebase.hook.tickets.process.delete');
        // A filter applied to the given area.
        $bundle->addType('ui.filter', 'knowledgebase.filterhook.tickets');
        $this->registerHookSubscriberBundle($bundle);

    }
}

