<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Form\Handler\User\Ticket;

use Guite\KnowledgeBaseModule\Form\Handler\User\Ticket\Base\EditHandler as BaseEditHandler;

/**
 * This handler class handles the page events of the Form called by the guiteKnowledgeBaseModule_user_edit() function.
 * It aims on the ticket object type.
 */
class EditHandler extends BaseEditHandler
{
    // feel free to extend the base handler class here
}
