<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */

class KnowledgeBase_Form_Plugin_FormFrame extends Zikula_Form_Plugin
{
    public $useTabs;
    public $cssClass = 'tabs';

    // Plugins MUST implement this function as it is stated here.
    // The information is used to re-establish the plugins on postback.
    function getFilename()
    {
        return __FILE__;
    }

    function create($view, &$params)
    {
        $this->useTabs = (array_key_exists('useTabs', $params) ? $params['useTabs'] : false);
    }


    // This is called by the framework before the content of the block is rendered
    function renderBegin($view)
    {
        $tabClass = $this->useTabs ? ' ' . $this->cssClass : '';
        return "<div class=\"knowledgebaseForm{$tabClass}\">\n";
    }

    // This is called by the framework after the content of the block is rendered
    function renderEnd($view)
    {
        return "</div>\n";
    }
}
