<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de) at Sat Mar 15 10:39:27 CET 2014.
 */

namespace Guite\KnowledgeBaseModule\Base;

use HookUtil;
use Zikula_AbstractVersion;
use Zikula\Component\HookDispatcher\ProviderBundle;
use Zikula\Component\HookDispatcher\SubscriberBundle;
use Zikula\Module\SearchModule\AbstractSearchable;

/**
 * Version information base class.
 */
class KnowledgeBaseModuleVersion extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '1.0.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Knowledge base');
        // the module description
        $meta['description']          = $this->__('The knowledge base module provides a categorised archive for recurring questions and answers to improve community support.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('knowledgebase');
        // core requirement
        $meta['core_min']             = '1.4.0'; // requires minimum 1.4.0 or later
        $meta['core_max']             = '1.4.99'; // not ready for 1.5.0 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
                          HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true),
                          AbstractSearchable::SEARCHABLE => array('class' => 'Guite\KnowledgeBaseModule\Helper\SearchHelper'),
/*,
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
                          'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'GuiteKnowledgeBaseModule::' => '::',
            'GuiteKnowledgeBaseModule::Ajax' => '::',
            'GuiteKnowledgeBaseModule:ItemListBlock:' => 'Block title::',
            'GuiteKnowledgeBaseModule:Ticket:' => 'Ticket ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
        
        $bundle = new SubscriberBundle($this->name, 'subscriber.guiteknowledgebasemodule.ui_hooks.tickets', 'ui_hooks', __('guiteknowledgebasemodule Tickets Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'guiteknowledgebasemodule.ui_hooks.tickets.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'guiteknowledgebasemodule.ui_hooks.tickets.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'guiteknowledgebasemodule.ui_hooks.tickets.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'guiteknowledgebasemodule.ui_hooks.tickets.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'guiteknowledgebasemodule.ui_hooks.tickets.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'guiteknowledgebasemodule.ui_hooks.tickets.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'guiteknowledgebasemodule.ui_hooks.tickets.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new SubscriberBundle($this->name, 'subscriber.guiteknowledgebasemodule.filter_hooks.tickets', 'filter_hooks', __('guiteknowledgebasemodule Tickets Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'guiteknowledgebasemodule.filter_hooks.tickets.filter');
        $this->registerHookSubscriberBundle($bundle);

        
    }
}
