<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Feb 17 14:43:00 CET 2011.
 */

/**
 * Business entity class for communication with controllers and encapsulating model details.
 *
 * This is the concrete business class for ticket entities.
 */
class KnowledgeBase_BusinessEntity_Ticket extends KnowledgeBase_BusinessEntity_Base_Ticket
{
    // feel free to add your own additions here
}
