<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Smarty function to process hierarchical list structures by given level information
 *
 * Available parameters:
 *   - assign:  If set, the result is assigned to the corresponding variable instead of printed out
 *
 * @param  array            $params All attributes passed to this function from the template.
 * @param  Zikula_Form_View $view   Reference to the view object.
 *
 * @return string List markup output.
 */
function smarty_function_kbProcessListLevels($params, &$view)
{
    if (!isset($params['level']) || !isset($params['lastlevel'])) {
        $render->trigger_error($view->__f('%1$s: missing parameter \'%2$s\'', array('smarty_function_kbProcessListLevels', 'lastlevel')));
    }

    $result = '';

    $level = (is_numeric($params['level'])) ? $params['level'] : count(explode('.', $params['level']));
    $lastLevel = (is_numeric($params['lastlevel'])) ? $params['lastlevel'] : count(explode('.', $params['lastlevel']));

    $opened = false;
    if ($lastLevel > 0) {
        if ($level > $lastLevel) {
            while ($level > $lastLevel) {
                $result .= '<ul>';
                $level--;
            }
            $opened = true;

        } elseif ($level < $lastLevel) {
            while ($level < $lastLevel) {
                $result .= '</li></ul>';
                $level++;
            }
        }
        if (!$opened) {
            $result .= '</li>';
        }
    }

    if (isset($assign)) {
        $smarty->assign($assign, $result);
        return;
    }

    return $result;
}
