<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Feb 17 14:43:00 CET 2011.
 */

/**
 * Model class that defines the entity structure and behaviours.
 *
 * This is the concrete table class for ticket entities.
 */
class KnowledgeBase_Model_Ticket extends KnowledgeBase_Model_Base_Ticket
{
    // feel free to add your own methods here
}
