<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */


/**
 * This is the Admin controller class providing navigation and interaction functionality.
 */
class KnowledgeBase_Controller_Admin extends KnowledgeBase_Controller_Base_Admin
{
    // feel free to add your own controller methods here
}
