<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 20:13:48 CET 2012.
 */


/**
 * This is the Admin controller class providing navigation and interaction functionality.
 */
class KnowledgeBase_Controller_Admin extends KnowledgeBase_Controller_Base_Admin
{
    // feel free to add your own controller methods here
}
