<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @link http://zikula.org
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger.
 * @url https://guite.de
 * @version Generated by ModuleStudio 0.5.2 (http://modulestudio.de) at Thu Jan 27 15:07:46 CET 2011.
 */


/**
 * This is the User controller class providing navigation and interaction functionality.
 */
class KnowledgeBase_Controller_User extends KnowledgeBase_Controller_Base_User
{
    /**
     * This method is the default function, and is called whenever the
     * module's User area is called without defining arguments.
     *
     * @params       TODO
     * @return mixed Output.
     */
    public function main($args)
    {
// DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('KnowledgeBase::', '::', ACCESS_OVERVIEW));
// DEBUG: permission check aspect ends

        $this->view->assign('categories', ModUtil::apiFunc('KnowledgeBase', 'user', 'getCategories', array('full' => false)));

        // fetch and return the appropriate template
        return KnowledgeBase_Util::processViewTemplate($this->view, 'user', '', 'main', $args);
    }
}
