<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Controller;

use Guite\KnowledgeBaseModule\Controller\Base\AjaxController as BaseAjaxController;

/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class AjaxController extends BaseAjaxController
{
    // feel free to add your own controller methods here
}
