<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Controller;

use Guite\KnowledgeBaseModule\Controller\Base\AjaxController as BaseAjaxController;

/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class AjaxController extends BaseAjaxController
{
    /**
     * Perform a "like this" operation increasing the ratesup field of corresponding ticket.
     *
     * @author       Axel Guckelsberger
     * @params       TODO
     * @return       Render output
     */
    public function like($args)
    {
        // DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('GuiteKnowledgeBaseModule::', '::', ACCESS_OVERVIEW));
        // DEBUG: permission check aspect ends

        $id = (int) FormUtil::getPassedValue('id', 0, 'POST', FILTER_VALIDATE_INT);
        if ($id > 0) {
            $entityClass = 'GuiteKnowledgeBaseModule:TicketEntity';
            $repository = $this->entityManager->getRepository($entityClass);

            $repository->incrementRatesUp($id);
        }

        return true;
    }


    /**
     * Perform a "dislike this" operation increasing the ratesdown field of corresponding ticket.
     *
     * @author       Axel Guckelsberger
     * @params       TODO
     * @return       Render output
     */
    public function dislike($args)
    {
        // DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('GuiteKnowledgeBaseModule::', '::', ACCESS_OVERVIEW));
        // DEBUG: permission check aspect ends

        $id = (int) FormUtil::getPassedValue('id', 0, 'POST', FILTER_VALIDATE_INT);
        if ($id > 0) {
            $entityClass = 'GuiteKnowledgeBaseModule:TicketEntity';
            $repository = $this->entityManager->getRepository($entityClass);

            $repository->incrementRatesDown($id);
        }

        return true;
    }
}
