<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Controller;

use Guite\KnowledgeBaseModule\Controller\Base\UserController as BaseUserController;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * This is the User controller class providing navigation and interaction functionality.
 */
class UserController extends BaseUserController
{
    /**
     * This method is the default function handling the user area called without defining arguments.
     *
     *
     * @return mixed Output.
     *
     * @throws AccessDeniedException Thrown if the user doesn't have required permissions
     */
    public function indexAction(Request $request)
    {
        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_OVERVIEW)) {
            throw new AccessDeniedException();
        }

        $this->view->assign('categories', ModUtil::apiFunc($this->name, 'user', 'getCategories', array('full' => false)));

        // fetch and return the appropriate template
        return $this->view->fetch('User/index.tpl');
    }
}
