<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Api;

use Guite\KnowledgeBaseModule\Api\Base\AdminApi as BaseAdminApi;

/**
 * This is the Admin api helper class.
 */
class AdminApi extends BaseAdminApi
{
    // feel free to add own api methods here
}
