<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger (Guite)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Guite\KnowledgeBaseModule\Api;

use Guite\KnowledgeBaseModule\Api\Base\CategoryApi as BaseCategoryApi;

/**
 * Category api implementation class.
 */
class CategoryApi extends BaseCategoryApi
{
    // feel free to extend the category api at this place
}
