<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 20:13:48 CET 2012.
 */


/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class KnowledgeBase_Controller_Ajax extends KnowledgeBase_Controller_Base_Ajax
{
    /**
     * Perform a "like this" operation increasing the ratesup field of corresponding ticket.
     *
     * @author       Axel Guckelsberger
     * @params       TODO
     * @return       Render output
     */
    public function like($args)
    {
        // DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('KnowledgeBase::', '::', ACCESS_OVERVIEW));
        // DEBUG: permission check aspect ends

        $id = (int) FormUtil::getPassedValue('id', 0, 'POST', FILTER_VALIDATE_INT);
        if ($id > 0) {
            $repository = $this->entityManager->getRepository('KnowledgeBase_Entity_Ticket');
            $repository->incrementRatesUp($id);
        }
        return true;
    }


    /**
     * Perform a "dislike this" operation increasing the ratesdown field of corresponding ticket.
     *
     * @author       Axel Guckelsberger
     * @params       TODO
     * @return       Render output
     */
    public function dislike($args)
    {
        // DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('KnowledgeBase::', '::', ACCESS_OVERVIEW));
        // DEBUG: permission check aspect ends

        $id = (int) FormUtil::getPassedValue('id', 0, 'POST', FILTER_VALIDATE_INT);
        if ($id > 0) {
            $repository = $this->entityManager->getRepository('KnowledgeBase_Entity_Ticket');
            $repository->incrementRatesDown($id);
        }
        return true;
    }
}
