<?php
/**
 * KnowledgeBase.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package KnowledgeBase
 * @author Axel Guckelsberger <info@guite.de>.
 * @link https://guite.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Wed Jan 04 20:13:48 CET 2012.
 */


/**
 * This is the User controller class providing navigation and interaction functionality.
 */
class KnowledgeBase_Controller_User extends KnowledgeBase_Controller_Base_User
{
    /**
     * This method is the default function, and is called whenever the
     * module's User area is called without defining arguments.
     *
     * @params       TODO
     * @return mixed Output.
     */
    public function main($args)
    {
        // DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('KnowledgeBase::', '::', ACCESS_OVERVIEW));
        // DEBUG: permission check aspect ends

        $this->view->assign('categories', ModUtil::apiFunc($this->name, 'user', 'getCategories', array('full' => false)));

        // fetch and return the appropriate template
        return $this->view->fetch('user/main.tpl');
    }
}
